name: CI

on:
  pull_request:

  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          cache-dependency-path: Sistema/pom.xml

      - name: Compilar y ejecutar tests
        working-directory: Sistema
        run: mvn clean install